//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UXiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_EStatusPedimento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAT_EStatusPedimento()
        {
            this.TblOrdenDeCompra = new HashSet<TblOrdenDeCompra>();
        }
    
        public int IdEstatusOC { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> UUM { get; set; }
        public Nullable<System.DateTime> FUM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblOrdenDeCompra> TblOrdenDeCompra { get; set; }
    }
}
