//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UXiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuentaUsuario
    {
        public int IdCuentaUsuario { get; set; }
        public int IdUsuario { get; set; }
        public Nullable<decimal> SaldoAFavor { get; set; }
        public Nullable<int> UUM { get; set; }
        public Nullable<System.DateTime> FUM { get; set; }
        public bool Activo { get; set; }
    
        public virtual UXI_Usuarios UXI_Usuarios { get; set; }
    }
}
