//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UXiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistorialSaldos
    {
        public int IdHistorial { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public int UUM { get; set; }
        public int IDTipoMovimiento { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public decimal Monto_Entrada { get; set; }
        public decimal Monto_Salida { get; set; }
    
        public virtual CAT_TiposMovimientos CAT_TiposMovimientos { get; set; }
        public virtual UXI_Usuarios UXI_Usuarios { get; set; }
    }
}
