//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UXiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MensajesOrdenes
    {
        public int IdMensaje { get; set; }
        public int IdUsuario { get; set; }
        public int IdOrdenCompra { get; set; }
        public string Mensaje { get; set; }
        public System.DateTime Fecha_Alta { get; set; }
    }
}
