//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UXiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblOrdenDeCompra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblOrdenDeCompra()
        {
            this.TblRelacionPedimento = new HashSet<TblRelacionPedimento>();
        }
    
        public int IdOrdenCompra { get; set; }
        public int IdUsuario { get; set; }
        public Nullable<int> IdZona { get; set; }
        public string ReferenciaBancaria { get; set; }
        public Nullable<decimal> Total { get; set; }
        public int IdEstatusOC { get; set; }
        public System.DateTime FechaOrden { get; set; }
        public System.DateTime FechaPagoMax { get; set; }
        public Nullable<System.DateTime> FUM { get; set; }
        public Nullable<int> UUM { get; set; }
    
        public virtual UXI_Usuarios UXI_Usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblRelacionPedimento> TblRelacionPedimento { get; set; }
        public virtual CAT_EStatusPedimento CAT_EStatusPedimento { get; set; }
    }
}
