//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UXiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblProductos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblProductos()
        {
            this.TblRelacionPedimento = new HashSet<TblRelacionPedimento>();
        }
    
        public int IdProducto { get; set; }
        public string SKU { get; set; }
        public string Descripcion_Corta { get; set; }
        public string Descripcion_Larga { get; set; }
        public Nullable<int> IdCategoria { get; set; }
        public Nullable<int> IdProveedor { get; set; }
        public string FacturaProveedor { get; set; }
        public Nullable<decimal> PrecioNeto { get; set; }
        public string Ubicacion { get; set; }
        public Nullable<System.DateTime> FUM { get; set; }
        public Nullable<int> UUM { get; set; }
        public Nullable<bool> Activo { get; set; }
    
        public virtual TblCategoria TblCategoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblRelacionPedimento> TblRelacionPedimento { get; set; }
    }
}
