//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UXiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblRelacionPedimento
    {
        public int IdODC { get; set; }
        public int IdOrdenCompra { get; set; }
        public int IdProducto { get; set; }
        public string SKU { get; set; }
        public Nullable<decimal> PrecioNeto { get; set; }
        public Nullable<decimal> PrecioVenta { get; set; }
        public int IdDescuento { get; set; }
        public decimal Total { get; set; }
        public System.DateTime FechaPedimento { get; set; }
        public int IdEstatusPedimento { get; set; }
        public string IMEI { get; set; }
        public Nullable<int> UUM { get; set; }
        public Nullable<System.DateTime> FUM { get; set; }
    
        public virtual TblOrdenDeCompra TblOrdenDeCompra { get; set; }
        public virtual TblProductos TblProductos { get; set; }
    }
}
