//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UXiModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblServicio_Precio_tipoUsuario
    {
        public int IDServicioPrecioUsuario { get; set; }
        public int IdProducto { get; set; }
        public int TipoCliente { get; set; }
        public Nullable<decimal> Precio { get; set; }
    }
}
